# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19WACZ13MRBHmwnOZf5JEcwqGGxsdKRLV
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import os,shutil,math,scipy,cv2
import numpy as np
import matplotlib.pyplot as plt
import random as rn



from time import time
from glob import glob
from tqdm import tqdm
from skimage.io import imread
from IPython.display import SVG

from scipy import misc,ndimage
from scipy.ndimage.interpolation import zoom
# from scipy.ndimage import imread

dict = {'bharatanatyam' : 0,
 'kathak' : 1,
 'kathakali' : 2,
 'kuchipudi' : 3,
 'manipuri' : 4,
 'mohiniyattam' : 5,
 'odissi' : 6,
 'sattriya' : 7}

img_dir = 'danceForms/test'
csv_file = 'danceForms/test.csv'
danceNames = pd.read_csv(csv_file)
danceNames = np.array(danceNames)

X = []
Z = []
name = []
imgsize = 224          #256,150,224

for img in tqdm(os.listdir(img_dir)):
    for item in danceNames:
        if item[0] == img:
            label = dict[item[1]]
            break
    
    print(img , item[1] , label)
    path = os.path.join(img_dir,img) 
    img = cv2.imread(path,cv2.IMREAD_COLOR)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    img = cv2.resize(img,(imgsize,imgsize))
    # plt.imshow(img)
    X.append(np.array(img))
    Z.append(label)

# X contains pixels and Z contains strings
# X,Z can be a normal list or a numpy array
# Z.append(np.string_(str))   use this to store strings

import numpy as np
import h5py


archive = h5py.File('train_224.h5', 'w')

archive.create_dataset('/X', data=X)
archive.create_dataset('/Z',data=Z)


archive.close()

dataset = h5py.File('train_224.h5', "r")

XX = dataset["X"][:]
ZZ = dataset["Z"][:]

print(XX.shape,ZZ.shape)
dataset.close()

# train_150
# train_256
# train_224